import turtle

turtle.speed(1000)

turtle.right(180)
turtle.fillcolor("blue")
turtle.pencolor("blue")
turtle.begin_fill()
turtle.circle(100, 20)
turtle.end_fill()
turtle.fillcolor("green")
turtle.pencolor("green")
turtle.begin_fill()
turtle.circle(100, 50)
turtle.end_fill()
turtle.fillcolor("orange")
turtle.pencolor("orange")
turtle.begin_fill()
turtle.circle(100, 70)
turtle.end_fill()
turtle.fillcolor("red")
turtle.pencolor("red")
turtle.begin_fill()
turtle.circle(100, 100)
turtle.end_fill()
turtle.fillcolor("#009eff")
turtle.pencolor("#009eff")
turtle.begin_fill()
turtle.circle(100, 120)
turtle.end_fill()

turtle.pencolor("white")
turtle.pensize(2)
turtle.begin_fill()
turtle.left(90)
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.end_fill()

turtle.fillcolor("red")
turtle.begin_fill()
turtle.left(180)
turtle.forward(100)
turtle.left(80)
turtle.forward(100)
turtle.end_fill()

turtle.fillcolor("orange")
turtle.begin_fill()
turtle.left(180)
turtle.forward(100)
turtle.left(110)
turtle.forward(100)
turtle.end_fill()

turtle.fillcolor("green")
turtle.begin_fill()
turtle.left(180)
turtle.forward(100)
turtle.left(130)
turtle.forward(100)
turtle.end_fill()

turtle.fillcolor("blue")
turtle.begin_fill()
turtle.left(180)
turtle.forward(100)
turtle.left(160)
turtle.forward(100)
turtle.end_fill()

turtle.up()
turtle.setposition(-20, 10)
turtle.pencolor("black")
turtle.write("E", move=False, align="left", font=("Arial", 7, "normal"))
turtle.setposition(-80, -20)
turtle.write("D", move=False, align="left", font=("Arial", 7, "normal"))
turtle.setposition(-110, -130)
turtle.write("C", move=False, align="left", font=("Arial", 7, "normal"))
turtle.setposition(20, -220)
turtle.write("B", move=False, align="left", font=("Arial", 7, "normal"))
turtle.setposition(100, -60)
turtle.write("A", move=False, align="left", font=("Arial", 7, "normal"))

turtle.done()